apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-services-to-floci
  namespace: cms
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: floci
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 4566
