apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "incident-bridge.fullname" . }}-config
  labels:
    {{- include "incident-bridge.labels" . | nindent 4 }}
data:
  AWS_ENDPOINT_URL: {{ .Values.global.aws.endpointUrl | quote }}
  AWS_DEFAULT_REGION: {{ .Values.global.aws.region | quote }}
  DYNAMODB_TABLE_NAME: {{ .Values.global.dynamodb.tableName | quote }}
