apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incident-bridge.fullname" . }}
  labels:
    {{- include "incident-bridge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "incident-bridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "incident-bridge.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: AWS_ENDPOINT_URL
              value: {{ .Values.global.aws.endpointUrl | quote }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.global.aws.region | quote }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.global.aws.accessKeyId | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.global.aws.secretAccessKey | quote }}
            - name: DYNAMODB_TABLE_NAME
              value: {{ .Values.global.dynamodb.tableName | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.healthCheck.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.readyPath }}
              port: {{ .Values.healthCheck.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
